apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ms
  template:
    metadata:
      labels:
        app: frontend-ms
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html
        configMap:
          name: frontend-index
